language: python
script: true
script:
  - python main.py

deploy:
  provider: releases
  api_key: "82f3f0e9dcdc01671da354af4b41898a0d1b4a24"
  file_glob: true
  file: file/*
  skip_cleanup: true
  on:
    tags: true
